project:
  type: book

book:
  title: "R, general notes"
  author: "JC"
  chapters:
    - index.qmd
    - Markdown.qmd
    - r_tidy_evaluation.qmd
    - Turning R functions into a package.qmd


format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
    css: dense-notes.css
